### ISSUE TITLE
NextJS and PWA compatability

### ISSUE THREAD

**Issue by winniepukki** [winniepukki/bonvoyage#17]
**Is your feature request related to a problem? Please describe.**
It is essential to understand whether the NextJS-based SPA's are compatible with the PWA technology. The PWA approach allows the app to be downloaded locally and then used with no Internet. Since Offline support is one of the key features of the app, this must be clearly researched and described during the Retrospective.

**Describe the solution you'd like**
Are the NextJS-based applications compatible with the PWA technology with no libraries or frameworks, and how to start?

**Describe alternatives you've considered**
Not applicable.

**Additional context**
- [ ] Can the PWA technology be implemented with no frameworks and libraries?
- [ ] Can this be done through the code, rather than the Vercel platform?
- [ ] How to supply the Service Worker?
- [ ] How to supply the Manifest file?

**Comment by ymarkoff** [comment]
**Is your feature request related to a problem? Please describe.**
Next.js is indeed a viable way to build a PWA. An example can be found [here](https://github.com/vercel/next.js/tree/canary/examples/progressive-web-app) . Offline support is achieved through service workers.

**Describe the solution you'd like**

Next.js 9.1 introduces the public directory support where we can store the files that will be mapped to the root of the domain. For example, if I'm running my application locally at http://localhost:3000 and store a file called sw.js inside public (public/sw.js) it will available at http://localhost:3000/sw.js. Therefore, we can reference it in our application and install the service worker without the need of a custom server.

**Additional context**
 _Can the PWA technology be implemented with no frameworks and libraries?_
yes, for a few Next.js versions now. An example can be found here https://github.com/ymarkoff/with-service-worker. 

_Can this be done through the code, rather than the Vercel platform?_
Yes, everything is done in the code and then built by the Vercel platform when committed to the main branch.

_How to supply the Service Worker?_
By adding it to the /public directory as mentioned above.
 
 _How to supply the Manifest file?_
By adding it to the /public folder and comiting to github.
